### ISSUE TITLE
Cannot achieve compilation

### ISSUE THREAD

**Issue by jamesnyika** [lambdahands/lt-scss#2]
First of all .. thanks a lot for the plugin.. it is brilliant.
I am able to successfully see the effects of evaluating the scss file but I cannot seem to =get  compilation (and I assume dumping of a css file) in the appropriate directory. 

![screen shot 2014-02-28 at 12 04 41 pm](https://f.cloud.github.com/assets/6818081/2296160/8092a572-a09a-11e3-905d-55ff72e6a7a9.png)

**Comment by jamesnyika** [comment]
Compile on save is turned on. I did not copy the configuration setting to the behaviours as you instructed.. I just assumed that since I could see the option to turn on the feature in the settings that it was there. Maybe that is the cause ?

**Comment by lambdahands** [comment]
Hey, glad to see you've got everything mostly up and running! There were some issues that weren't ironed out concerning file compilation. You should now be able to toggle compilation without adding the behavior (you were right to assume this wasn't the case before.)

Would you mind cloning the latest repo into your plugins folder and verifying everything is working? ~~I'll be updating to `0.0.2` once I'm certain this has been resolved~~.

**Comment by lambdahands** [comment]
Just pushed a fix that should allow for compilation in any circumstance (even if you're not connected to a browser). Closing this for now!
